spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/themepark_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: themepark_local_user
    password: themepark1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # Spring Boot2부터 default DBCP는 hikariCP 이다.
      maximum-pool-size: 20             # pool에 보관 가능한 최대 connection 수
  batch:
    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 실행한다. 임베디드인 경우에는 기본적으로 실행하는데, always 설정하면 임베디드 타입처럼 항상 활성화시킬 수 있다.
      # 초기 수행한 이후에는 꺼두어도 된다.
      initialize-schema: always